//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projeto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projeto()
        {
            this.Vaga = new HashSet<Vaga>();
        }
    
        public int Id { get; set; }
        public int CategoriaProjetoId { get; set; }
        public int UsuarioId { get; set; }
        public string Nome { get; set; }
        public string Sobre { get; set; }
        public Nullable<int> Progresso { get; set; }
        public string Descricao { get; set; }
    
        public virtual CategoriaProjeto CategoriaProjeto { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vaga> Vaga { get; set; }
    }
}
