//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamUp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeamUpContext : DbContext
    {
        public TeamUpContext()
            : base("name=TeamUpContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aplicacao> aplicacao { get; set; }
        public virtual DbSet<CategoriaProjeto> categoria_projeto { get; set; }
        public virtual DbSet<Notificacao> notificacao { get; set; }
        public virtual DbSet<Projeto> projeto { get; set; }
        public virtual DbSet<Usuario> usuario { get; set; }
        public virtual DbSet<Vaga> vaga { get; set; }
    }
}
